[project]
name = "cellprofiler_cellpose"
version = "4.2.8"
description = "CellProfiler and Cellpose, living together"
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[feature.mysql.target.unix.activation]
# https://github.com/PyMySQL/mysqlclient/issues/496#issuecomment-1614688099
env = { MYSQLCLIENT_CFLAGS = "-I$PIXI_PROJECT_ROOT/.pixi/envs/default/include/mysql", MYSQLCLIENT_LDFLAGS = "-L$PIXI_PROJECT_ROOT/.pixi/envs/default/lib -lmysqlclient -rpath $PIXI_PROJECT_ROOT/.pixi/envs/default/lib" }

# usage of `%` or `$` and `\\` or `/` will depend on if using e.g. cmd.exe or git bash or ...
[feature.java.target.win-64.activation]
env = { JAVA_HOME = "%PIXI_PROJECT_ROOT%\\.pixi\\envs\\default\\Library\\lib\\jvm", JDK_HOME = "%PIXI_PROJECT_ROOT%\\.pixi\\envs\\default\\Library\\lib\\jvm" }

[feature.java.activation]
env = { JAVA_HOME = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/jvm", JDK_HOME = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/jvm" }

[pypi-dependencies]
cellprofiler = "==4.2.8"
cellpose = "<4"

[dependencies]
matplotlib = ">=3.1.3,<3.8"
pywavelets = "<1.6"
boto3 = ">=1.12.28,<1.16.63"
setuptools = "64.*"
tifffile = "<2022.4.22"
scipy = "==1.9.0"
numpy = ">=1.20.1,<1.25.0"
contourpy = "==1.1.1"
"scikit-image" = "==0.18.3"
"scikit-learn" = ">=0.20,<1"
h5py = "<3.7"

[target.win-64.dependencies]
python = "3.8.*"

[target.unix.dependencies]
python = "3.9.*"

[target.osx.dependencies]
"python.app" = ">=1.4,<2"

[target.osx-arm64.pypi-dependencies]
wxPython = "==4.2.1"

# enable this to avoid building wxPython wheel on Linux
# disable to build wheel from scratch
# url must be changed to match linux distro: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/
[target.linux-64.pypi-dependencies]
wxPython = { url = "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.2-cp39-cp39-linux_x86_64.whl" }

[feature.mysql.dependencies]
wheel = ">=0.45.0, <0.46"
mysql = "=8.0"

[feature.mysql.pypi-options]
no-build-isolation = ["mysqlclient"]

[feature.java.dependencies]
openjdk = "11.*"
maven = ">=3.9.9,<4"

[environments]
default = ["mysql","java"]
